---
title: "Final Report for Intro to Data Science"
output: html_notebook
---


```{r}
library(tidyverse)
myurl <- "https://github.com/JoseNpoly/datasets/blob/master/worldcup.csv"
mydata <- read.csv(myurl)
```

```{r}
worldcup
```

```{r}
arrange(worldcup, Team, Position, Time, Shots)
```

```{r}
arrange(worldcup, desc(Passes))
```

```{r}
select(worldcup,
      Passes:Tackles,
      ends_with("Time"),
      Saves,
      Shots)
```



```{r}
worldcup_data = select(worldcup,
                       Passes:Tackles,
                       ends_with("Time"),
                       Saves,
                       Shots)
```



```{r}
mutate(worldcup_data,
       intercept = Passes - Tackles,
       goalkeeper_inter = Shots - Saves
       )
```


```{r}
summarise(worldcup, pass = mean(Passes, na.rm = TRUE))
```


```{r}
worldcup %>%
  group_by(Time) %>%
  summarize(
    count = n(),
    avg = mean(Tackles, na.rm = TRUE)
  )
```
```{r}
head(worldcup, 10)
```

```{r}
filter(worldcup, Position == "Midfielder", Team == "Ghana")
```

```{r}
Player_pos = worldcup %>%
  filter(Position == "Defender")
Player_pos
```












